### PR TITLE
Implement Custom Button

### PR DESCRIPTION
**Pull request by OnyekachiSamuel**
#### What this PR is about?
Implemented a custom button type with image initializer

#### Ticket
[Here](https://trello.com/c/JcmifVID/48-refactor-buttons-with-images-to-use-a-new-uiimagebutton-object)

### CODE REVIEW

**Comment by kutan74** [comment]
Creating a static UIButton extension method that returns UIImageButton instance would be very helpful for the future. Something like that maybe https://gist.github.com/kutan74/7145a8e1e0885e33d873f17d73f8f9ba

**Comment by OnyekachiSamuel** [comment]
> Creating a static UIButton extension method that returns UIImageButton instance would be very helpful for the future. Something like that maybe https://gist.github.com/kutan74/7145a8e1e0885e33d873f17d73f8f9ba

Thanks for your suggestion @kutan74 , I will update my pr.

**Comment by kutan74** [comment]
@OnyekachiSamuel yeah I agree it'd make things more complicated.

**Comment by evilpenguin** [comment]
Why was this closed?

**Comment by hybridcattt** [comment]
can the branch deleted? the code is present on development

**Pull request closed without merging**
