### PR TITLE
[DELETE] Removed PersonDetailsController with associated xib

### PR DESCRIPTION
**Pull request by Sharkesm**
Note: It was confirmed by the design team that we no longer need `PersonDetails` screen

### CODE REVIEW

**Comment by dasautoooo** [comment]
Think this can be done in #75 . It doesn't matter if delete those files now or later alone with #75 being merged.
Maybe we close it?

**Comment by evilpenguin** [comment]
Are we closing this?

**Comment by dasautoooo** [comment]
The changes are already in #88. 
Closed it.

**Comment by Sharkesm** [comment]
@dasautoooo Great catch :))

**Pull request closed without merging**
