### PR TITLE
[FEAT] Implement search feature

### PR DESCRIPTION
**Pull request by FranckNdame**
## About
- A quick and scrappy way to search for a person.
- Deleted the search Bar view and replaced it with a controller.

| Before | After | 
|:------:|:------:|
|IMG_3722|IMG_3723|

### CODE REVIEW

**Comment by IgnatovPasha** [comment]
Hey! There is a conflict which should be resolved before this branch could be tested. 
BTW I can resolve it. But there is another issue - as pagination is used now in HomeController to fetch people then your current implementation will only fetch first page. Could you revise fetching approach?

**Comment by IgnatovPasha** [comment]
resolved conflicts

**Comment by ohwhen** [comment]
Should we close this PR?

**Comment by evilpenguin** [comment]
Please do not delete the branch.

**Pull request closed without merging**
