### PR TITLE
Person Controller - Programmatic UI 

### PR DESCRIPTION
**Pull request by FranckNdame**

### CODE REVIEW

**Comment by biscuitehh** [comment]
Screen Shot 2020-06-05 at 6 56 22 PM

**Comment by biscuitehh** [comment]
Screen Shot 2020-06-05 at 6 56 20 PM

**Comment by Sharkesm** [comment]
Great addition to everyone who contributed on this branch, Kudos 🔥 and will make some code base organisation then proceed setting this bad boi up for a review.

**Comment by dasautoooo** [comment]
Great Job! ✨

**Pull request merged**
