### PR TITLE
[BUG] - Fix auto-layout breaks & minor design detail

### PR DESCRIPTION
**Pull request by biscuitehh**
Bugfix - the collection view cell broke text constraints while scrolling, which can lead to performance degradation and unexpected layout behavior. I updated several of the constraints and adjusted the cell height to match designs + fix the issue.

### CODE REVIEW

**Comment by biscuitehh** [comment]
Screen Shot 2020-06-07 at 5 30 47 AM
Note: there are still some constraint issues with the navigation bar that I'd like to address in a follow-up PR.

**Comment by bertadevant** [comment]
Could you add a bit description what was the problem and how you fixed it? To make review faster

**Comment by biscuitehh** [comment]
@bertadevant updated - let me know if that's clear enough!

**Comment by tomke100** [comment]
I want my live back and i delete the foto

**Comment by tomke100** [comment]
I do nothing wrong and i dont go to the cops i want my thinks back

**Comment by tomke100** [comment]
I am tired

**Pull request merged**
