### PR TITLE
[CHORE] Adding Indonesian 🇮🇩 Localization

### PR DESCRIPTION
**Pull request by thatswiftdev**

### CODE REVIEW

**Comment by hybridcattt** [comment]
Could you send me your email address so I can invite you to our localization service where we enter the translations? 
Then we have a script that pulls from there. The process is described here: https://saytheirnames.slack.com/archives/C014X94AEUR/p1591983765022900

**Comment by thatswiftdev** [comment]
Hey, @hybridcattt . My email is bayu99070@gmail.com. Thanks!

**Comment by hybridcattt** [comment]
@sikubay done :)

**Review by Sharkesm — APPROVED** [review]
LGTM🎊

**Comment by Sharkesm** [comment]
And resolve the conflicts

**Review by hybridcattt — APPROVED** [review]
Let's add it to the script as well? Not blocking though and can be a followup :)

**Pull request closed without merging**
