### PR TITLE
Change path in Github Action

### PR DESCRIPTION
**Pull request by Mackis**
Attempting to address SwiftLint warnings included in SwiftLint Github action.

- Updated the path to the yaml file with excluded

### CODE REVIEW

**Comment by rodericj** [comment]
Oh what are the warnings?

**Comment by Mackis** [comment]
> Oh what are the warnings?

Looked at some PRs and saw warnings appearing on libraries. Also excluded paths to the test files don't know if that's something we want.

**Comment by rodericj** [comment]
I’m wondering if they are up to date with this one https://github.com/Say-Their-Name/say-their-names-ios/pull/63. That was meant to address it. Are you seeing Pod/ getting linted?

**Comment by Mackis** [comment]
> I’m wondering if they are up to date with this one #63. That was meant to address it. Are you seeing Pod/ getting linted?

Yeah have a look at #62

**Comment by rodericj** [comment]
Got it. Are you open to rebasing that branch from the latest? I’m nearly certain those are fixed. I’m on mobile. Otherwise I could do it. I can try in the morning probably if you or she doesn’t.

**Comment by Mackis** [comment]
Looking at the last build pods are still being linted. Trying now with the `config` argument on the action. 
Screenshot 2020-06-05 at 06 57 26

@rodericj do you mean I should rebase #62 into this branch?

**Comment by rodericj** [comment]
@Mackis close, I was suggesting that we rebase the latest stuff from development onto the diffable PR #62. I just did that, and it now seems to be running the linter changes from this afternoon and I'm not seeing any linter warnings on that PR anymore. 

In other words, that PR went up before the linter modifications took place this afternoon so it didn't have the benefit of the change.

**Comment by Mackis** [comment]
Oh I see no need for this diff then all seems to be in order. Thanks @rodericj

**Pull request closed without merging**
