### PR TITLE
Fixing the linter

### PR DESCRIPTION
**Pull request by rodericj**

### CODE REVIEW

**Comment by rodericj** [comment]
@evilpenguin it's no longer a draft I believe.

**Comment by evilpenguin** [comment]
> @evilpenguin it's no longer a draft I believe.
Ready for review?

**Comment by rodericj** [comment]
No I take it back. It looked like the linter rules were passing, now they are not. Standby again.

**Comment by evilpenguin** [comment]
Np. Just add the `review me` label when you are ready, and request `Say-Their-Name/ios`.

**Comment by rodericj** [comment]
Ok I think we are in good shape for a review now. @evilpenguin I can't actually change the labels. I think I'm not part of the club yet. 

https://github.com/norio-nomura/action-swiftlint/issues/23

**Comment by rodericj** [comment]
Linking to the original linter PR https://github.com/Say-Their-Name/say-their-names-ios/pull/46

Also I think this is no longer out of date from development.

**Pull request merged**
